
# constraints

# ad9361 master

set_property -dict {PACKAGE_PIN V23 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ref_clk_p]
set_property -dict {PACKAGE_PIN W24 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports ref_clk_n]

set_property -dict {PACKAGE_PIN AF20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_0_p]
set_property -dict {PACKAGE_PIN AG20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_0_n]
set_property -dict {PACKAGE_PIN AG21 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_0_p]
set_property -dict {PACKAGE_PIN AH21 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_0_n]
set_property -dict {PACKAGE_PIN AK17 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_0_p[0]}]
set_property -dict {PACKAGE_PIN AK18 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_0_n[0]}]
set_property -dict {PACKAGE_PIN AH19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_0_p[1]}]
set_property -dict {PACKAGE_PIN AJ19 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_0_n[1]}]
set_property -dict {PACKAGE_PIN AJ20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_0_p[2]}]
set_property -dict {PACKAGE_PIN AK20 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_0_n[2]}]
set_property -dict {PACKAGE_PIN AH23 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_0_p[3]}]
set_property -dict {PACKAGE_PIN AH24 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_0_n[3]}]
set_property -dict {PACKAGE_PIN AG22 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_0_p[4]}]
set_property -dict {PACKAGE_PIN AH22 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_0_n[4]}]
set_property -dict {PACKAGE_PIN AJ23 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_0_p[5]}]
set_property -dict {PACKAGE_PIN AJ24 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_0_n[5]}]
set_property -dict {PACKAGE_PIN AF19 IOSTANDARD LVDS_25} [get_ports tx_clk_out_0_p]
set_property -dict {PACKAGE_PIN AG19 IOSTANDARD LVDS_25} [get_ports tx_clk_out_0_n]
set_property -dict {PACKAGE_PIN AD21 IOSTANDARD LVDS_25} [get_ports tx_frame_out_0_p]
set_property -dict {PACKAGE_PIN AE21 IOSTANDARD LVDS_25} [get_ports tx_frame_out_0_n]
set_property -dict {PACKAGE_PIN AG24 IOSTANDARD LVDS_25} [get_ports {tx_data_out_0_p[0]}]
set_property -dict {PACKAGE_PIN AG25 IOSTANDARD LVDS_25} [get_ports {tx_data_out_0_n[0]}]
set_property -dict {PACKAGE_PIN AD23 IOSTANDARD LVDS_25} [get_ports {tx_data_out_0_p[1]}]
set_property -dict {PACKAGE_PIN AE23 IOSTANDARD LVDS_25} [get_ports {tx_data_out_0_n[1]}]
set_property -dict {PACKAGE_PIN AF23 IOSTANDARD LVDS_25} [get_ports {tx_data_out_0_p[2]}]
set_property -dict {PACKAGE_PIN AF24 IOSTANDARD LVDS_25} [get_ports {tx_data_out_0_n[2]}]
set_property -dict {PACKAGE_PIN AA22 IOSTANDARD LVDS_25} [get_ports {tx_data_out_0_p[3]}]
set_property -dict {PACKAGE_PIN AA23 IOSTANDARD LVDS_25} [get_ports {tx_data_out_0_n[3]}]
set_property -dict {PACKAGE_PIN AC24 IOSTANDARD LVDS_25} [get_ports {tx_data_out_0_p[4]}]
set_property -dict {PACKAGE_PIN AD24 IOSTANDARD LVDS_25} [get_ports {tx_data_out_0_n[4]}]
set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVDS_25} [get_ports {tx_data_out_0_p[5]}]
set_property -dict {PACKAGE_PIN Y23 IOSTANDARD LVDS_25} [get_ports {tx_data_out_0_n[5]}]

set_property -dict {PACKAGE_PIN T24 IOSTANDARD LVCMOS25} [get_ports {gpio_status_0[0]}]
set_property -dict {PACKAGE_PIN T25 IOSTANDARD LVCMOS25} [get_ports {gpio_status_0[1]}]
set_property -dict {PACKAGE_PIN U25 IOSTANDARD LVCMOS25} [get_ports {gpio_status_0[2]}]
set_property -dict {PACKAGE_PIN V26 IOSTANDARD LVCMOS25} [get_ports {gpio_status_0[3]}]
set_property -dict {PACKAGE_PIN W29 IOSTANDARD LVCMOS25} [get_ports {gpio_status_0[4]}]
set_property -dict {PACKAGE_PIN W30 IOSTANDARD LVCMOS25} [get_ports {gpio_status_0[5]}]
set_property -dict {PACKAGE_PIN V27 IOSTANDARD LVCMOS25} [get_ports {gpio_status_0[6]}]
set_property -dict {PACKAGE_PIN W28 IOSTANDARD LVCMOS25} [get_ports {gpio_status_0[7]}]
set_property -dict {PACKAGE_PIN P25 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl_0[0]}]
set_property -dict {PACKAGE_PIN P26 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl_0[1]}]
set_property -dict {PACKAGE_PIN T30 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl_0[2]}]
set_property -dict {PACKAGE_PIN U30 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl_0[3]}]
set_property -dict {PACKAGE_PIN T29 IOSTANDARD LVCMOS25} [get_ports gpio_en_agc_0]
set_property -dict {PACKAGE_PIN W25 IOSTANDARD LVCMOS25} [get_ports mcs_sync]
set_property -dict {PACKAGE_PIN W26 IOSTANDARD LVCMOS25} [get_ports gpio_resetb_0]
set_property -dict {PACKAGE_PIN AA24 IOSTANDARD LVCMOS25} [get_ports enable_0]
set_property -dict {PACKAGE_PIN AB24 IOSTANDARD LVCMOS25} [get_ports txnrx_0]
set_property -dict {PACKAGE_PIN V28 IOSTANDARD LVCMOS25} [get_ports gpio_debug_1_0]
set_property -dict {PACKAGE_PIN V29 IOSTANDARD LVCMOS25} [get_ports gpio_debug_2_0]
set_property -dict {PACKAGE_PIN R28 IOSTANDARD LVCMOS25} [get_ports gpio_calsw_1_0]
set_property -dict {PACKAGE_PIN T28 IOSTANDARD LVCMOS25} [get_ports gpio_calsw_2_0]
set_property -dict {PACKAGE_PIN P30 IOSTANDARD LVCMOS25} [get_ports gpio_ad5355_rfen]
set_property -dict {PACKAGE_PIN P21 IOSTANDARD LVCMOS25} [get_ports gpio_ad5355_lock]

# spi

set_property PACKAGE_PIN R25 [get_ports spi_ad9361_0]
set_property IOSTANDARD LVCMOS25 [get_ports spi_ad9361_0]
set_property PULLUP true [get_ports spi_ad9361_0]
set_property PACKAGE_PIN R26 [get_ports spi_ad9361_1]
set_property IOSTANDARD LVCMOS25 [get_ports spi_ad9361_1]
set_property PULLUP true [get_ports spi_ad9361_1]
set_property PACKAGE_PIN P23 [get_ports spi_ad5355]
set_property IOSTANDARD LVCMOS25 [get_ports spi_ad5355]
set_property PULLUP true [get_ports spi_ad5355]
set_property -dict {PACKAGE_PIN P24 IOSTANDARD LVCMOS25} [get_ports spi_clk]
set_property -dict {PACKAGE_PIN N29 IOSTANDARD LVCMOS25} [get_ports spi_mosi]
set_property -dict {PACKAGE_PIN P29 IOSTANDARD LVCMOS25} [get_ports spi_miso]

# ad9361 slave

set_property -dict {PACKAGE_PIN AE13 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_1_p]
set_property -dict {PACKAGE_PIN AF13 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_clk_in_1_n]
set_property -dict {PACKAGE_PIN AF15 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_1_p]
set_property -dict {PACKAGE_PIN AG15 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports rx_frame_in_1_n]
set_property -dict {PACKAGE_PIN AE12 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_1_p[0]}]
set_property -dict {PACKAGE_PIN AF12 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_1_n[0]}]
set_property -dict {PACKAGE_PIN AG12 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_1_p[1]}]
set_property -dict {PACKAGE_PIN AH12 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_1_n[1]}]
set_property -dict {PACKAGE_PIN AJ15 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_1_p[2]}]
set_property -dict {PACKAGE_PIN AK15 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_1_n[2]}]
set_property -dict {PACKAGE_PIN AE16 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_1_p[3]}]
set_property -dict {PACKAGE_PIN AE15 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_1_n[3]}]
set_property -dict {PACKAGE_PIN AB12 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_1_p[4]}]
set_property -dict {PACKAGE_PIN AC12 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_1_n[4]}]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_1_p[5]}]
set_property -dict {PACKAGE_PIN AA14 IOSTANDARD LVDS_25 DIFF_TERM 1} [get_ports {rx_data_in_1_n[5]}]
set_property -dict {PACKAGE_PIN AD14 IOSTANDARD LVDS_25} [get_ports tx_clk_out_1_p]
set_property -dict {PACKAGE_PIN AD13 IOSTANDARD LVDS_25} [get_ports tx_clk_out_1_n]
set_property -dict {PACKAGE_PIN AH14 IOSTANDARD LVDS_25} [get_ports tx_frame_out_1_p]
set_property -dict {PACKAGE_PIN AH13 IOSTANDARD LVDS_25} [get_ports tx_frame_out_1_n]
set_property -dict {PACKAGE_PIN AC14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_1_p[0]}]
set_property -dict {PACKAGE_PIN AC13 IOSTANDARD LVDS_25} [get_ports {tx_data_out_1_n[0]}]
set_property -dict {PACKAGE_PIN AJ16 IOSTANDARD LVDS_25} [get_ports {tx_data_out_1_p[1]}]
set_property -dict {PACKAGE_PIN AK16 IOSTANDARD LVDS_25} [get_ports {tx_data_out_1_n[1]}]
set_property -dict {PACKAGE_PIN AD16 IOSTANDARD LVDS_25} [get_ports {tx_data_out_1_p[2]}]
set_property -dict {PACKAGE_PIN AD15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_1_n[2]}]
set_property -dict {PACKAGE_PIN AH17 IOSTANDARD LVDS_25} [get_ports {tx_data_out_1_p[3]}]
set_property -dict {PACKAGE_PIN AH16 IOSTANDARD LVDS_25} [get_ports {tx_data_out_1_n[3]}]
set_property -dict {PACKAGE_PIN AF18 IOSTANDARD LVDS_25} [get_ports {tx_data_out_1_p[4]}]
set_property -dict {PACKAGE_PIN AF17 IOSTANDARD LVDS_25} [get_ports {tx_data_out_1_n[4]}]
set_property -dict {PACKAGE_PIN AB15 IOSTANDARD LVDS_25} [get_ports {tx_data_out_1_p[5]}]
set_property -dict {PACKAGE_PIN AB14 IOSTANDARD LVDS_25} [get_ports {tx_data_out_1_n[5]}]

set_property -dict {PACKAGE_PIN AH26 IOSTANDARD LVCMOS25} [get_ports {gpio_status_1[0]}]
set_property -dict {PACKAGE_PIN AH27 IOSTANDARD LVCMOS25} [get_ports {gpio_status_1[1]}]
set_property -dict {PACKAGE_PIN AG26 IOSTANDARD LVCMOS25} [get_ports {gpio_status_1[2]}]
set_property -dict {PACKAGE_PIN AG27 IOSTANDARD LVCMOS25} [get_ports {gpio_status_1[3]}]
set_property -dict {PACKAGE_PIN AH28 IOSTANDARD LVCMOS25} [get_ports {gpio_status_1[4]}]
set_property -dict {PACKAGE_PIN AH29 IOSTANDARD LVCMOS25} [get_ports {gpio_status_1[5]}]
set_property -dict {PACKAGE_PIN AK27 IOSTANDARD LVCMOS25} [get_ports {gpio_status_1[6]}]
set_property -dict {PACKAGE_PIN AK28 IOSTANDARD LVCMOS25} [get_ports {gpio_status_1[7]}]
set_property -dict {PACKAGE_PIN AJ26 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl_1[0]}]
set_property -dict {PACKAGE_PIN AK26 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl_1[1]}]
set_property -dict {PACKAGE_PIN AF30 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl_1[2]}]
set_property -dict {PACKAGE_PIN AG30 IOSTANDARD LVCMOS25} [get_ports {gpio_ctl_1[3]}]
set_property -dict {PACKAGE_PIN AF29 IOSTANDARD LVCMOS25} [get_ports gpio_en_agc_1]
set_property -dict {PACKAGE_PIN AE25 IOSTANDARD LVCMOS25} [get_ports gpio_resetb_1]
set_property -dict {PACKAGE_PIN AE18 IOSTANDARD LVCMOS25} [get_ports enable_1]
set_property -dict {PACKAGE_PIN AE17 IOSTANDARD LVCMOS25} [get_ports txnrx_1]
set_property -dict {PACKAGE_PIN AJ28 IOSTANDARD LVCMOS25} [get_ports gpio_debug_3_1]
set_property -dict {PACKAGE_PIN AJ29 IOSTANDARD LVCMOS25} [get_ports gpio_debug_4_1]
set_property -dict {PACKAGE_PIN AJ30 IOSTANDARD LVCMOS25} [get_ports gpio_calsw_3_1]
set_property -dict {PACKAGE_PIN AK30 IOSTANDARD LVCMOS25} [get_ports gpio_calsw_4_1]

# clocks

create_clock -period 4.000 -name rx_0_clk [get_ports rx_clk_in_0_p]
create_clock -period 4.000 -name rx_1_clk [get_ports rx_clk_in_1_p]
create_clock -period 4.000 -name ref_clk [get_ports ref_clk_p]




# constraints

# hdmi

set_property -dict {PACKAGE_PIN P28 IOSTANDARD LVCMOS25} [get_ports hdmi_out_clk]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports hdmi_vsync]
set_property -dict {PACKAGE_PIN R22 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports hdmi_hsync]
set_property -dict {PACKAGE_PIN V24 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports hdmi_data_e]
set_property -dict {PACKAGE_PIN U24 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[0]}]
set_property -dict {PACKAGE_PIN T22 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[1]}]
set_property -dict {PACKAGE_PIN R23 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[2]}]
set_property -dict {PACKAGE_PIN AA25 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[3]}]
set_property -dict {PACKAGE_PIN AE28 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[4]}]
set_property -dict {PACKAGE_PIN T23 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[5]}]
set_property -dict {PACKAGE_PIN AB25 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[6]}]
set_property -dict {PACKAGE_PIN T27 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[7]}]
set_property -dict {PACKAGE_PIN AD26 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[8]}]
set_property -dict {PACKAGE_PIN AB26 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[9]}]
set_property -dict {PACKAGE_PIN AA28 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[10]}]
set_property -dict {PACKAGE_PIN AC26 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[11]}]
set_property -dict {PACKAGE_PIN AE30 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[12]}]
set_property -dict {PACKAGE_PIN Y25 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[13]}]
set_property -dict {PACKAGE_PIN AA29 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[14]}]
set_property -dict {PACKAGE_PIN AD30 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[15]}]
set_property -dict {PACKAGE_PIN Y28 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[16]}]
set_property -dict {PACKAGE_PIN AF28 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[17]}]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[18]}]
set_property -dict {PACKAGE_PIN AA27 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[19]}]
set_property -dict {PACKAGE_PIN U22 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[20]}]
set_property -dict {PACKAGE_PIN N28 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[21]}]
set_property -dict {PACKAGE_PIN V21 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[22]}]
set_property -dict {PACKAGE_PIN AC22 IOSTANDARD LVCMOS25 IOB TRUE} [get_ports {hdmi_data[23]}]

# spdif

set_property -dict {PACKAGE_PIN AC21 IOSTANDARD LVCMOS25} [get_ports spdif]

# iic

set_property PACKAGE_PIN AJ14 [get_ports iic_scl]
set_property IOSTANDARD LVCMOS25 [get_ports iic_scl]
set_property PULLUP true [get_ports iic_scl]
set_property PACKAGE_PIN AJ18 [get_ports iic_sda]
set_property IOSTANDARD LVCMOS25 [get_ports iic_sda]
set_property PULLUP true [get_ports iic_sda]

# gpio (switches, leds and such)

set_property -dict {PACKAGE_PIN AB17 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[0]}]
set_property -dict {PACKAGE_PIN AC16 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[1]}]
set_property -dict {PACKAGE_PIN AC17 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[2]}]
set_property -dict {PACKAGE_PIN AJ13 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[3]}]
set_property -dict {PACKAGE_PIN AK25 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[4]}]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS15} [get_ports {gpio_bd[5]}]
set_property -dict {PACKAGE_PIN R27 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[6]}]

set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[7]}]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD LVCMOS15} [get_ports {gpio_bd[8]}]
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS25} [get_ports {gpio_bd[9]}]
set_property -dict {PACKAGE_PIN A17 IOSTANDARD LVCMOS15} [get_ports {gpio_bd[10]}]

set_property -dict {PACKAGE_PIN H14 IOSTANDARD LVCMOS15} [get_ports {gpio_bd[11]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS15} [get_ports {gpio_bd[12]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS15} [get_ports {gpio_bd[13]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS15} [get_ports {gpio_bd[14]}]

# Define SPI clock
create_clock -period 40.000 -name spi0_clk [get_pins -hier */EMIOSPI0SCLKO]
create_clock -period 40.000 -name spi1_clk [get_pins -hier */EMIOSPI1SCLKO]




create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 16384 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list i_system_wrapper/system_i/axi_ad9361_0/inst/i_dev_if/i_clk/clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[0]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[1]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[2]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[3]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[4]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[5]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[6]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[7]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[8]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[9]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[10]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[11]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[12]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[13]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[14]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[0]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[1]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[2]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[3]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[4]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[5]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[6]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[7]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[8]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[9]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[10]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[11]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[12]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[13]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[14]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[0]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[1]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[2]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[3]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[4]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[5]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[6]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[7]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[8]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[9]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[10]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[11]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[12]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[13]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[14]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q0[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[0]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[1]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[2]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[3]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[4]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[5]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[6]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[7]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[8]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[9]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[10]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[11]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[12]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[13]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[14]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_q1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[0]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[1]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[2]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[3]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[4]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[5]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[6]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[7]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[8]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[9]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[10]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[11]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[12]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[13]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[14]} {i_system_wrapper/system_i/axi_ad9361_0_adc_data_i0[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[0]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[1]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[2]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[3]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[4]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[5]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[6]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[7]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[8]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[9]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[10]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[11]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[12]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[13]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[14]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i0[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[0]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[1]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[2]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[3]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[4]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[5]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[6]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[7]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[8]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[9]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[10]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[11]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[12]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[13]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[14]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_i1[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[0]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[1]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[2]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[3]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[4]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[5]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[6]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[7]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[8]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[9]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[10]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[11]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[12]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[13]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[14]} {i_system_wrapper/system_i/axi_ad9361_1_adc_data_q0[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list i_system_wrapper/system_i/axi_ad9361_0_adc_valid_i0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list i_system_wrapper/system_i/axi_ad9361_1_adc_valid_i0]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk]
